name: New release
on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  create_tag_release:
    name: Create Tag and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create tag
        id: create_tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a v${{ steps.get_version.outputs.version }} -m "Release v${{ steps.get_version.outputs.version }}"

      - name: Push tag
        run: git push origin ${{ steps.create_tag.outputs.tag }}

      - name: Get commit messages since last tag
        id: get_commit_messages
        run: |
          TAG=$(git describe --tags --abbrev=0)
          COMMIT_MESSAGES=$(git log $TAG..HEAD --pretty=format:"%s")
          echo "::set-output name=commit_messages::${COMMIT_MESSAGES}"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.S_GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: |
            ${{ join(steps.get_commit_messages.outputs.commit_messages, '\n') }}
          draft: false
          prerelease: false

      - name: Get Release ID
        id: get_release_id
        run: echo "::set-output name=release_id::${{ steps.create_release.outputs.release_id }}"

  publish-npm:
    name: Publish to npm registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public --scope=@thinkwik/sleep
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}